
apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-k8s12
spec:
  replicas: 6
  selector:
    matchLabels:
      app: project-k8s12
  template:
    metadata:
      labels:
        app: project-k8s12
    spec:
      containers:
      - name: project-k8s12
        image: mohamedsaad96/nodejs9:${IMAGE_TAG}
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: project-k8s12
spec:
  type: LoadBalancer 
  selector:
    app: project-k8s12
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000 #container port
    nodePort: 30080
